import headerGradient from "@/assets/header-gradient.svg";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative">
      <Providers>
        <body
          className={`${inter.className} bg-LIGHT_MAIN_BG dark:bg-DARK_MAIN_BG font-inter antialiased`}
        >
          <Image
            className="w-full absolute top-0 select-none -mt-20 -z-20"
            src={headerGradient}
            alt="blur header"
          />

          <Header />

          {children}

          <Footer />
        </body>
      </Providers>
    </html>
  );
}
